{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'they are equal'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def greater(a,b):\n",
    "    if a > b:\n",
    "        return a\n",
    "    elif a < b:\n",
    "        return b\n",
    "    else:\n",
    "        return \"they are equal\"\n",
    "\n",
    "greater(3,3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.123s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greatest(arr):\n",
    "    return max(arr,key=len)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\ipykernel_36872\\717276356.py\", line 2, in greatest\n",
      "    return max(arr,key=len)\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.166s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(arr):\n",
    "    sum_1=0\n",
    "    for i in arr:\n",
    "        sum_1+=i\n",
    "    return sum_1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.103s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "12"
      ]
     },
     "execution_count": 84,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def mult_all(arr):\n",
    "    x=1\n",
    "    for i in arr:\n",
    "        x*=i\n",
    "    return x\n",
    "mult_all([2,3,2])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.100s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 122,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def oper_all(arr, oper):\n",
    "    x=1\n",
    "    y=0\n",
    "    \n",
    "    if oper == \"+\":\n",
    "        for i in arr:\n",
    "            y+=i\n",
    "        return y\n",
    "    if oper ==\"*\":\n",
    "        for i in arr:\n",
    "            x*=i\n",
    "        return x\n",
    "            \n",
    "arr1=[1,2,2]            \n",
    "oper_all(arr1,\"*\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.113s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "120"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def factorial(n):\n",
    "    fact=1   \n",
    "    for i in range(1,n+1):\n",
    "        fact = fact * i\n",
    "    return fact\n",
    "factorial(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.122s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[2, 3, 4]"
      ]
     },
     "execution_count": 109,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def unique(arr):\n",
    "    list1= []\n",
    "    list1.append(arr[0])\n",
    "    \n",
    "    \n",
    "    for i in arr[1:]:\n",
    "        if i in list1:\n",
    "            pass\n",
    "        else:\n",
    "            list1.append(i)\n",
    "    return list1\n",
    "            \n",
    "arr1 = [2,2,2,3,4,4]\n",
    "unique(arr1)\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.251s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 171,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[3, 4, 5]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "5"
      ]
     },
     "execution_count": 171,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def mode_counter(arr):\n",
    "    counter=0\n",
    "    counter_max=0\n",
    "    mode=0\n",
    "    y = list(set(arr))\n",
    "    print(y)\n",
    "    for i in y:\n",
    "            counter=0\n",
    "            for a in arr:\n",
    "                if i==a:\n",
    "                    counter+=1\n",
    "                    if counter_max < counter:\n",
    "                        counter_max = counter\n",
    "                        mode = i\n",
    "                    else:\n",
    "                        pass\n",
    "                else:\n",
    "                    pass\n",
    "    return mode\n",
    "            \n",
    "    \n",
    " \n",
    "x =[5,5,5,5,3,3,3,4,4]\n",
    "mode_counter(x)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 172,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.100s\n",
      "\n",
      "OK\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n",
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 193,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.8660254037844386"
      ]
     },
     "execution_count": 193,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from statistics import stdev\n",
    "\n",
    "def st_dev(arr):\n",
    "\n",
    "    avg=sum(arr2)/len(arr2)\n",
    "\n",
    "    d=0\n",
    "    for i in arr2:\n",
    "        d +=(i-avg)**2\n",
    "        \n",
    "    return (d/len(arr2))**0.5\n",
    "    \n",
    "\n",
    "arr2=[2,4,2,2]    \n",
    "st_dev(arr2) \n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 195,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 640.753978911316 within 5 delta (639.8879535075316 difference) : Should be 640.753978911316\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 590.691501713101 within 5 delta (589.8254763093166 difference) : Should be 590.691501713101\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 560.8258661125041 within 5 delta (559.9598407087196 difference) : Should be 560.8258661125041\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 602.7238633936463 within 5 delta (601.8578379898619 difference) : Should be 602.7238633936463\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 531.7392834079684 within 5 delta (530.873258004184 difference) : Should be 531.7392834079684\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 652.9863121149814 within 5 delta (652.120286711197 difference) : Should be 652.9863121149814\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 544.1344287910338 within 5 delta (543.2684033872494 difference) : Should be 544.1344287910338\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 550.8092636532424 within 5 delta (549.943238249458 difference) : Should be 550.8092636532424\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 557.163755626109 within 5 delta (556.2977302223246 difference) : Should be 557.163755626109\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 594.3052701708306 within 5 delta (593.4392447670461 difference) : Should be 594.3052701708306\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 583.2918202344754 within 5 delta (582.425794830691 difference) : Should be 583.2918202344754\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 558.2221916526823 within 5 delta (557.3561662488979 difference) : Should be 558.2221916526823\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 680.566853750785 within 5 delta (679.7008283470005 difference) : Should be 680.566853750785\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 607.8024834006571 within 5 delta (606.9364579968727 difference) : Should be 607.8024834006571\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 618.1509848525775 within 5 delta (617.2849594487931 difference) : Should be 618.1509848525775\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 520.2329997709036 within 5 delta (519.3669743671192 difference) : Should be 520.2329997709036\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 651.8754927626258 within 5 delta (651.0094673588413 difference) : Should be 651.8754927626258\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 535.2674720797694 within 5 delta (534.401446675985 difference) : Should be 535.2674720797694\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 596.2796317218534 within 5 delta (595.413606318069 difference) : Should be 596.2796317218534\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 542.9969125684082 within 5 delta (542.1308871646238 difference) : Should be 542.9969125684082\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 558.8369051328496 within 5 delta (557.9708797290651 difference) : Should be 558.8369051328496\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 547.2445515445276 within 5 delta (546.3785261407431 difference) : Should be 547.2445515445276\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 640.3508111108493 within 5 delta (639.4847857070649 difference) : Should be 640.3508111108493\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 617.408418759864 within 5 delta (616.5423933560796 difference) : Should be 617.408418759864\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 608.5086235311745 within 5 delta (607.6425981273901 difference) : Should be 608.5086235311745\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 573.8187556064321 within 5 delta (572.9527302026477 difference) : Should be 573.8187556064321\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 589.428208506999 within 5 delta (588.5621831032146 difference) : Should be 589.428208506999\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 585.3110015969274 within 5 delta (584.444976193143 difference) : Should be 585.3110015969274\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 436.5368363881902 within 5 delta (435.67081098440576 difference) : Should be 436.5368363881902\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 549.1763796509409 within 5 delta (548.3103542471565 difference) : Should be 549.1763796509409\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 582.7770953436167 within 5 delta (581.9110699398323 difference) : Should be 582.7770953436167\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 613.0433409890645 within 5 delta (612.1773155852801 difference) : Should be 613.0433409890645\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 594.5053096637496 within 5 delta (593.6392842599652 difference) : Should be 594.5053096637496\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 577.2225343545301 within 5 delta (576.3565089507457 difference) : Should be 577.2225343545301\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 503.60028742540396 within 5 delta (502.73426202161954 difference) : Should be 503.60028742540396\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 560.362641255812 within 5 delta (559.4966158520276 difference) : Should be 560.362641255812\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 630.8134790597047 within 5 delta (629.9474536559203 difference) : Should be 630.8134790597047\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 632.7898458500966 within 5 delta (631.9238204463122 difference) : Should be 632.7898458500966\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 592.4650427940231 within 5 delta (591.5990173902387 difference) : Should be 592.4650427940231\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 544.6388497588716 within 5 delta (543.7728243550872 difference) : Should be 544.6388497588716\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 484.7457991524201 within 5 delta (483.87977374863567 difference) : Should be 484.7457991524201\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 549.4951901190437 within 5 delta (548.6291647152593 difference) : Should be 549.4951901190437\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 565.593250490138 within 5 delta (564.7272250863535 difference) : Should be 565.593250490138\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 558.2673450699302 within 5 delta (557.4013196661458 difference) : Should be 558.2673450699302\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 575.2578015683978 within 5 delta (574.3917761646134 difference) : Should be 575.2578015683978\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 622.4057153424359 within 5 delta (621.5396899386515 difference) : Should be 622.4057153424359\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 572.7649520157102 within 5 delta (571.8989266119257 difference) : Should be 572.7649520157102\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 606.356802079907 within 5 delta (605.4907766761226 difference) : Should be 606.356802079907\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 547.183624182495 within 5 delta (546.3175987787106 difference) : Should be 547.183624182495\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 577.6080292110173 within 5 delta (576.7420038072329 difference) : Should be 577.6080292110173\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 539.1064649882296 within 5 delta (538.2404395844452 difference) : Should be 539.1064649882296\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 558.3188415715118 within 5 delta (557.4528161677274 difference) : Should be 558.3188415715118\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 608.4110376903185 within 5 delta (607.5450122865341 difference) : Should be 608.4110376903185\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 584.1116555986025 within 5 delta (583.2456301948181 difference) : Should be 584.1116555986025\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 532.4660947443639 within 5 delta (531.6000693405795 difference) : Should be 532.4660947443639\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 555.3394915566971 within 5 delta (554.4734661529127 difference) : Should be 555.3394915566971\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 588.5898402113309 within 5 delta (587.7238148075464 difference) : Should be 588.5898402113309\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 561.8333901572831 within 5 delta (560.9673647534987 difference) : Should be 561.8333901572831\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 632.3197853741489 within 5 delta (631.4537599703644 difference) : Should be 632.3197853741489\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 546.7346643771656 within 5 delta (545.8686389733812 difference) : Should be 546.7346643771656\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 619.1447482602478 within 5 delta (618.2787228564633 difference) : Should be 619.1447482602478\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 615.979602441549 within 5 delta (615.1135770377646 difference) : Should be 615.979602441549\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 630.5129087389248 within 5 delta (629.6468833351404 difference) : Should be 630.5129087389248\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 534.422873505687 within 5 delta (533.5568481019026 difference) : Should be 534.422873505687\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 519.863964164774 within 5 delta (518.9979387609895 difference) : Should be 519.863964164774\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 505.9835372815997 within 5 delta (505.1175118778153 difference) : Should be 505.9835372815997\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 637.0435377758865 within 5 delta (636.1775123721021 difference) : Should be 637.0435377758865\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 550.3402664921232 within 5 delta (549.4742410883388 difference) : Should be 550.3402664921232\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 578.659214268578 within 5 delta (577.7931888647936 difference) : Should be 578.659214268578\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 536.4973005238588 within 5 delta (535.6312751200744 difference) : Should be 536.4973005238588\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 571.9951665776865 within 5 delta (571.1291411739021 difference) : Should be 571.9951665776865\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 599.3198409672447 within 5 delta (598.4538155634602 difference) : Should be 599.3198409672447\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 590.0849468038008 within 5 delta (589.2189214000164 difference) : Should be 590.0849468038008\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 537.4820670133771 within 5 delta (536.6160416095927 difference) : Should be 537.4820670133771\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 591.4316742780746 within 5 delta (590.5656488742902 difference) : Should be 591.4316742780746\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 484.34197769813863 within 5 delta (483.4759522943542 difference) : Should be 484.34197769813863\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 581.0618301095566 within 5 delta (580.1958047057722 difference) : Should be 581.0618301095566\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 533.1764531172867 within 5 delta (532.3104277135022 difference) : Should be 533.1764531172867\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 576.7594106701772 within 5 delta (575.8933852663928 difference) : Should be 576.7594106701772\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 584.5588582330599 within 5 delta (583.6928328292755 difference) : Should be 584.5588582330599\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 518.4070798633915 within 5 delta (517.541054459607 difference) : Should be 518.4070798633915\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 521.932615354473 within 5 delta (521.0665899506886 difference) : Should be 521.932615354473\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 603.0162466513569 within 5 delta (602.1502212475725 difference) : Should be 603.0162466513569\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 528.1289928608664 within 5 delta (527.262967457082 difference) : Should be 528.1289928608664\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 585.9457828961885 within 5 delta (585.079757492404 difference) : Should be 585.9457828961885\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 545.0928502416954 within 5 delta (544.226824837911 difference) : Should be 545.0928502416954\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 500.41938364117107 within 5 delta (499.55335823738665 difference) : Should be 500.41938364117107\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 545.6093549912504 within 5 delta (544.743329587466 difference) : Should be 545.6093549912504\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 539.1303491117277 within 5 delta (538.2643237079433 difference) : Should be 539.1303491117277\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 592.2951382700925 within 5 delta (591.4291128663081 difference) : Should be 592.2951382700925\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 587.1859064490516 within 5 delta (586.3198810452672 difference) : Should be 587.1859064490516\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 587.0547763688805 within 5 delta (586.1887509650961 difference) : Should be 587.0547763688805\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 579.1997620762926 within 5 delta (578.3337366725082 difference) : Should be 579.1997620762926\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 615.1950703279869 within 5 delta (614.3290449242024 difference) : Should be 615.1950703279869\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 552.2840402017263 within 5 delta (551.4180147979419 difference) : Should be 552.2840402017263\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 536.7001237598356 within 5 delta (535.8340983560512 difference) : Should be 536.7001237598356\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 567.686302301291 within 5 delta (566.8202768975066 difference) : Should be 567.686302301291\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 612.2253774718203 within 5 delta (611.3593520680358 difference) : Should be 612.2253774718203\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 615.2191447350393 within 5 delta (614.3531193312549 difference) : Should be 615.2191447350393\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 0.8660254037844386 != 567.6103051051298 within 5 delta (566.7442797013454 difference) : Should be 567.6103051051298\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.117s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once. Mind that the strings may contain characters that are not letters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 216,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'its a pangram'"
      ]
     },
     "execution_count": 216,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def pangram(string1):\n",
    "    import string\n",
    "    abc= string.ascii_lowercase[:]\n",
    "    for i in abc:\n",
    "        if i in string1:\n",
    "            pass\n",
    "        else:\n",
    "            return \"not\"\n",
    "            break\n",
    "    return (\"its a pangram\")# example of range of the alphabet from \"a\" to \"b\"\n",
    "        \n",
    "#pangram (\"Jock nymphs waqf drug vex blitz\")\n",
    "\n",
    "pangram (\"abcdefghijklmnopqrstuvwxyz\")   \n",
    "    \n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 214,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'its a pangram' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'its a pangram' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'its a pangram' != True : Should be True\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Usuario\\Desktop\\lectures\\lab-functions\\mod\\testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: 'not' != False : Should be False\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.033s\n",
      "\n",
      "FAILED (failures=30)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not.\n",
    "`Valid special characters: # @ ! $ % & ( ) ^ * [ ] { }`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
